#!/bin/bash
# ============================================================================
# DESPLIEGUE RÁPIDO A NETLIFY — Guía paso a paso
# ============================================================================

echo "🚀 BAJA eco-volt — Despliegue a Netlify"
echo ""
echo "Opción 1: Usar Netlify CLI (más rápido) ⚡"
echo "==========================================="
echo ""
echo "1. Instala Netlify CLI:"
echo "   npm install -g netlify-cli"
echo ""
echo "2. Inicia sesión en Netlify:"
echo "   netlify login"
echo ""
echo "3. Despliega este sitio:"
echo "   netlify deploy --prod"
echo ""
echo "✅ Tu sitio estará en línea en minutos con URL personalizada"
echo ""
echo ""
echo "Opción 2: Usar GitHub + Netlify UI (más control) 🐙"
echo "===================================================="
echo ""
echo "1. Crea un repo en GitHub:"
echo "   - Ve a https://github.com/new"
echo "   - Nombre: baja-ecovolt"
echo "   - Descripción: Landing page de ventas con agente interactivo"
echo "   - Click 'Create repository'"
echo ""
echo "2. Sube el código desde tu máquina:"
echo "   git remote add origin https://github.com/TU-USUARIO/baja-ecovolt.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Conecta a Netlify:"
echo "   - Ve a https://app.netlify.com"
echo "   - Click 'New site from Git'"
echo "   - Selecciona GitHub como proveedor"
echo "   - Selecciona tu repo 'baja-ecovolt'"
echo "   - Netlify detectará automáticamente la configuración"
echo "   - Click 'Deploy site'"
echo ""
echo "✅ Tu sitio tendrá URL automática (ej: baja-ecovolt-abc123.netlify.app)"
echo ""
echo ""
echo "📝 Próximos pasos después de desplegar:"
echo "======================================"
echo "1. Configura tu endpoint de Formspree (README.md sección 'Configuración')"
echo "2. Los formularios capturarán automáticamente en Netlify Forms"
echo "3. Opcionalmente, configura dominio personalizado en Netlify"
echo ""
